## 1 question 

In [1]:
import pandas as pd
import numpy as np
import mlxtend

In [15]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [209]:
data = pd.read_csv(r"C:\Users\Shivani Dussa\Downloads\retail.csv")

In [210]:
print(data.shape)
data.head()

(4539, 4)


POS Txn                       Dept   ID  Sales U
0  16120100160021008773               0261:HOSIERY  250        2
1  16120100160021008773  0634:VITAMINS & HLTH AIDS  102        1
2  16120100160021008773          0879:PET SUPPLIES  158        2
3  16120100160021008773                 0973:CANDY  175        2
4  16120100160021008773               0982:SPIRITS  176        1

In [211]:
#1.Remove the ‘0999: UNSCANNED ITEMS’ from the ‘Dept’ column
remove_col = data[data['Dept'] == '0999:UNSCANNED ITEMS']
remove_col

POS Txn                  Dept   ID  Sales U
764   16120100160023004258  0999:UNSCANNED ITEMS  182        1
2220  16120100160034005104  0999:UNSCANNED ITEMS  182        1
2237  16120100160034005109  0999:UNSCANNED ITEMS  182        1
2719  16120100160036007342  0999:UNSCANNED ITEMS  182        1
2977  16120100160037008773  0999:UNSCANNED ITEMS  182        1
3326  16120100160038001216  0999:UNSCANNED ITEMS  182        1
3515  16120100160038001286  0999:UNSCANNED ITEMS  182        1
3746  16120100160077007453  0999:UNSCANNED ITEMS  182        1
3803  16120100160077007533  0999:UNSCANNED ITEMS  182        1
3866  16120100160078001243  0999:UNSCANNED ITEMS  182        1
3919  16120100160079001388  0999:UNSCANNED ITEMS  182        1
4018  16120100160094009539  0999:UNSCANNED ITEMS  182        1
4119  16120100160094009611  0999:UNSCANNED ITEMS  182        1

In [7]:
remove_col.shape

(13, 4)

In [220]:
list = remove_col.values.tolist()
list

[[16120100160023004258, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160034005104, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160034005109, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160036007342, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160037008773, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160038001216, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160038001286, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160077007453, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160077007533, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160078001243, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160079001388, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160094009539, '0999:UNSCANNED ITEMS', 182, 1],
 [16120100160094009611, '0999:UNSCANNED ITEMS', 182, 1]]

In [225]:
list.remove('0999:UNSCANNED ITEMS')
print(list)

In [4]:
sr1 = data.drop(data.index[data['Dept'] == '0999:UNSCANNED ITEMS'],inplace = True)

In [5]:
data1 = data[data['Dept'] == '0999:UNSCANNED ITEMS']

In [6]:
data1

Empty DataFrame
Columns: [POS Txn, Dept, ID, Sales U]
Index: []

In [7]:
data.shape

(4526, 4)

In [8]:
# print no.of times 0973:CANDY was sold
candy_soldout = data[data['Dept'] == '0973:CANDY']
candy_soldout.head()

POS Txn        Dept   ID  Sales U
3   16120100160021008773  0973:CANDY  175        2
30  16120100160021008781  0973:CANDY  175        1
35  16120100160021008783  0973:CANDY  175        2
45  16120100160021008788  0973:CANDY  175        1
75  16120100160021008798  0973:CANDY  175        2

In [9]:
candy_soldout.shape[0]

275

In [193]:
candy_soldout = candy_soldout.shape[0]

- Total 275 times 0973:CANDY was sold out 

In [38]:
#2. For the Frequent Itemsets, keep the minimum support as 0.02 and find maximum support. (up to 5 decimal places)

In [19]:
# group the data by POS Txn
group_by = data.groupby('POS Txn')

In [20]:
group_by.first()

Dept   ID  Sales U
POS Txn                                                      
16120100160021008773               0261:HOSIERY  250        2
16120100160021008774           0597:HEALTH AIDS   93        1
16120100160021008775      0819:PRE-RECORDED A/V  135        1
16120100160021008776     0961:GENERAL GROCERIES  169        3
16120100160021008777               0982:SPIRITS  176        2
...                                         ...  ...      ...
16120100160162000842     0815:AUDIO ELECTRONICS  132        1
16120100160162000843  0857:PC PERIPH/OFFICE ACC  155        1
16120100160162000845   0395:MENS ATHLETIC SHOES   49        1
16120100160162000846    0532:AMERICAN GREETINGS   72        1
16120100160221001467  0066:VENDING/AMUSEMENT MA  242        1

[2064 rows x 3 columns]

In [54]:
from mlxtend.frequent_patterns import apriori

In [21]:
import apyori
from apyori import apriori

In [100]:
# all the itemsets for each group in a list(itemsets)
frequent_itemsets = apriori(data, min_support=0.4509,use_colnames=True)
frequent_itemsets = list(frequent_itemsets)

In [101]:
#Use TransactionEncoder() to transform the list(itemsets)
from mlxtend.preprocessing import TransactionEncoder
transformed = TransactionEncoder()
transformed_list = transformed.fit(data).transform(data)
transformed_list

array([[ True, False, False, ..., False, False,  True],
       [False,  True, False, ..., False,  True, False],
       [False,  True,  True, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [23]:
transformed_list.astype("int")

array([[1, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [105]:
#covert the tranformed list to a dataframe
import pandas as pd
transformed_df = pd.DataFrame(transformed_list,columns = transformed.columns_)

In [106]:
#Apply the apriori algorithm using parameters
apriori_alg = apriori(transformed_df, min_support=0.02, use_colnames=True)

In [143]:
#Find the max_support upto 5 decimal places
from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_itemset, metric="lift", min_threshold=2)

In [137]:
for item in frequent_itemsets:

    # first index of the inner list
    # Contains base item and add item
    pair = item[1] 
    items = [x for x in pair]
    #print("Rule: " + items[0] + " -> " + items[0])

    #second index of the inner list
    print("Support: " + str(item[0]))

In [140]:
item

RelationRecord(items=frozenset({' '}), support=0.5, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({' '}), confidence=0.5, lift=1.0)])

In [52]:
frequent_itemset = pd.DataFrame(frequent_itemsets)
frequent_itemsets = frequent_itemset.rename(columns = {'items' : 'itemsets', 'support' : 'support','ordered_statistics':'ordered_statistics'}, inplace = True)

In [ ]:
#Filter rules having lift>=3  and confidence >=0.1 

In [164]:
rules[(rules['confidence'] >= 0.1)]

antecedents consequents  antecedent support  consequent support  support  \
0         (S)         ( )                 0.5                 0.5      0.5   
1         ( )         (S)                 0.5                 0.5      0.5   

   confidence  lift  leverage  conviction  
0         1.0   2.0      0.25         inf  
1         1.0   2.0      0.25         inf

In [146]:
rules[(rules['lift'] >= 3.0)]

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, leverage, conviction]
Index: []

In [174]:
filtered_rules = rules[(rules['antecedent support'] > 0.1) &
                  (rules['consequent support'] > 0.4)]

In [186]:
number_of_rules = 2
filtered_rules = 2

In [202]:
output = candy_soldout,Max_support,number_of_rules,filtered_rules

In [203]:
output

(275, 0.5248, 2, 2)

In [ ]:
output.to_csv("output/output.csv")

### 2 question

In [55]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv")

In [4]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.shape

(768, 9)

In [5]:
import sklearn.preprocessing
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [6]:
X = df.drop(['Outcome'],axis = 1)
y = df['Outcome']

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [56]:
X_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
464           10      115             98              0        0  24.0   
223            7      142             60             33      190  28.8   
393            4      116             72             12       87  22.1   
766            1      126             60              0        0  30.1   
570            3       78             70              0        0  32.5   

     DiabetesPedigreeFunction  Age  
464                     1.022   34  
223                     0.687   61  
393                     0.463   37  
766                     0.349   47  
570                     0.270   39

In [9]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((514, 8), (514,), (254, 8), (254,))

In [57]:
X_test.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
668            6       98             58             33      190  34.0   
324            2      112             75             32        0  35.7   
624            2      108             64              0        0  30.8   
690            8      107             80              0        0  24.6   
473            7      136             90              0        0  29.9   

     DiabetesPedigreeFunction  Age  
668                     0.430   43  
324                     0.148   21  
624                     0.158   21  
690                     0.856   34  
473                     0.210   50

In [16]:
y_test.head()

668    0
324    0
624    0
690    0
473    0
Name: Outcome, dtype: int64

In [11]:
import sklearn
from sklearn import ensemble
from sklearn.ensemble import AdaBoostClassifier

In [58]:
# Find optimal values for Adaboost
from sklearn.ensemble import AdaBoostClassifier
abr = AdaBoostClassifier(learning_rate = 0.3,n_estimators = 100,random_state = 42)

abr.fit(X_train,y_train)
#y_pred1 = abr.predict(X_test)
#y_pred1train = abr.predict(X_train)

AdaBoostClassifier(learning_rate=0.3, n_estimators=100, random_state=42)

In [123]:
optimal_values = 0.3,100

- Optimal Values are 0.3 and 100

In [59]:
# use gridsearch cv
from sklearn.model_selection import GridSearchCV 
from sklearn.ensemble import AdaBoostClassifier

param_grid = {'n_estimators':[50,100],
    'learning_rate':[0.3,0.4],
              'random_state':[42]
}
abr_grid = GridSearchCV(estimator = abr,param_grid = param_grid,cv = 5)

abr_grid.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=AdaBoostClassifier(learning_rate=0.3, n_estimators=100,
                                          random_state=42),
             param_grid={'learning_rate': [0.3, 0.4], 'n_estimators': [50, 100],
                         'random_state': [42]})

In [41]:
# find the precision values for Adaboost
from sklearn.metrics import accuracy_score
from sklearn.ensemble import AdaBoostClassifier
abr = AdaBoostClassifier(learning_rate = 0.3,n_estimators = 100,random_state = 42)

abr.fit(X_train,y_train)
y_pred = abr.predict(X_test)
Accuracy = accuracy_score(y_test,y_pred)
print(Accuracy)

0.7480314960629921


In [82]:
cm1 = confusion_matrix(y_test,y_pred)
#print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))

#from confusion matrix calculate accuracy
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('AdaBoost_Accuracy : ', accuracy1)

# sensitivity
sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('AdaBoost_Sensitivity : ', sensitivity1 )

# specificity
specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('AdaBoost_Specificity : ', specificity1)

AdaBoost_Accuracy :  0.7480314960629921
AdaBoost_Sensitivity :  0.8273809523809523
AdaBoost_Specificity :  0.5930232558139535


In [62]:
# finding the precision values of GradientBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
Gradboost = GradientBoostingClassifier(n_estimators = 100,learning_rate = 0.3,)
Gradboost.fit(X_train,y_train)
y_pred1 = Gradboost.predict(X_test)
Accuracy = accuracy_score(y_test,y_pred1)
Accuracy

0.7125984251968503

In [118]:
cm2 = confusion_matrix(y_test,y_pred1)
#print('Confusion Matrix : \n', cm2)

total1=sum(sum(cm2))

#from confusion matrix calculate accuracy
accuracy2=(cm2[0,0]+cm2[1,1])/total1
print('GradBoost_Accuracy : ', accuracy2)

# sensitivity
sensitivity2 = cm2[0,0]/(cm2[0,0]+cm2[0,1])
print('GradBoost_Sensitivity : ', sensitivity2)

# specificity
specificity2 = cm2[1,1]/(cm2[1,0]+cm2[1,1])
print('GradBoost_Specificity : ', specificity2)

GradBoost_Accuracy :  0.7125984251968503
GradBoost_Sensitivity :  0.7619047619047619
GradBoost_Specificity :  0.6162790697674418


- optimal values are 0.3, 100

In [92]:
AdaBoost_Accuracy =  accuracy1
AdaBoost_Accuracy

0.7480314960629921

In [114]:
AdaBoost_Accuracy = round(AdaBoost_Accuracy,2)
print(AdaBoost_Accuracy)

GradBoost_Accuracy = accuracy2
GradBoost_Accuracy = round(GradBoost_Accuracy,2)
print(GradBoost_Accuracy)

0.75
0.71


In [116]:
AdaBoost_Sensitivity =  sensitivity1
AdaBoost_Sensitivity = round(AdaBoost_Sensitivity,2)
print(AdaBoost_Sensitivity)

GradBoost_Sensitivity =  sensitivity2
GradBoost_Sensitivity = round(GradBoost_Sensitivity,2)
print(GradBoost_Sensitivity)

0.83
0.76


In [117]:
AdaBoost_Specificity =  specificity1
AdaBoost_Specificity = round(AdaBoost_Specificity,2)
print(AdaBoost_Specificity)

GradBoost_Specificity = specificity2 
GradBoost_Specificity = round(GradBoost_Specificity,2)
print(GradBoost_Specificity)

0.59
0.62


- Accuracy is more for  Ada Boost
- Senitivity is more for Ada Boost
- Specificity is more for Gradient Boost 

In [122]:
output = AdaBoost_Accuracy,AdaBoost_Sensitivity,GradBoost_Specificity

In [126]:
final_output = optimal_values + output

In [127]:
final_output

(0.3, 100, 0.75, 0.83, 0.62)

In [ ]:
final_output.to_csv("output/output.csv")